[font]
size = 7.0

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
family = "Terminus"
style = "Bold"

[font.italic]
family = "Terminus"
style = "Light"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#e6e6e6"

#[colors.selection]
#text = "#000000"
#background = "#ffffff"

#[colors.normal]
#black = "#000000"
#red = "#1a1a1a"
#green = "#333333"
#yellow = "#4d4d4d"
#blue = "#666666"
#magenta = "#808080"
#cyan = "#b3b3b3"
#white = "#d9d9d9"

#[colors.bright]
#black = "#1a1a1a"
#red = "#333333"
#green = "#4d4d4d"
#yellow = "#808080"
#blue = "#b3b3b3"
#magenta = "#cccccc"
#cyan = "#e6e6e6"
#white = "#ffffff"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "On"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[bell]
animation = "EaseOutSine"
color = "#e4c9af"
duration = 1

[window]
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 80
lines = 24

[general]
live_config_reload = true
#import = ["~/.config/alacritty/deep-purple.toml", "~/.config/alacritty/fonts.toml"]

[terminal]
